# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7e51e7c13e47bab868307bc00d241b1214dfc014c919fc545247b9ffd81a5fe4f98078fc84518a23f3fd5e14701b2cc97274096dbd8b60205ba649557371002

test:
  secret_key_base: caea324e80ec3463acbd8c609595916ca6c25c8f5dd7d3a71b78715f591aa8e6200495137981796f6c9d9016455762cff95d67aa635ad3778bf83e01cbb111ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
